/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_pnrs1_projekat_MyNDK */

#ifndef _Included_com_example_pnrs1_projekat_MyNDK
#define _Included_com_example_pnrs1_projekat_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_pnrs1_projekat_MyNDK
 * Method:    increment
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_pnrs1_1projekat_MyNDK_increment
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
